CC = gcc
CFLAGS = -O2 -Iinclude -Wall
BIN_DIR = bin
SRC_DIR = src

all: setup $(BIN_DIR)/sensors.exe $(BIN_DIR)/broker.exe $(BIN_DIR)/dispatcher.exe $(BIN_DIR)/monitor.exe

setup:
	@if not exist $(BIN_DIR) mkdir $(BIN_DIR)

$(BIN_DIR)/sensors.exe: $(SRC_DIR)/modulo1_sensors/sensors.c
	$(CC) $(CFLAGS) $(SRC_DIR)/modulo1_sensors/sensors.c -o $@

$(BIN_DIR)/broker.exe: $(SRC_DIR)/modulo2_broker/broker.c
	$(CC) $(CFLAGS) $(SRC_DIR)/modulo2_broker/broker.c -o $@

$(BIN_DIR)/dispatcher.exe: $(SRC_DIR)/modulo3_dispatcher/dispatcher.c
	$(CC) $(CFLAGS) $(SRC_DIR)/modulo3_dispatcher/dispatcher.c -o $@

$(BIN_DIR)/monitor.exe: $(SRC_DIR)/modulo4_monitor/monitor.c
	$(CC) $(CFLAGS) $(SRC_DIR)/modulo4_monitor/monitor.c -o $@

clean:
	@if exist $(BIN_DIR) rmdir /s /q $(BIN_DIR)